package output

import (
	"fmt"
	"strings"

	"github.com/guilherme11gr/crivo/internal/domain"
)

// GenerateMarkdown creates a PR-ready markdown report
func GenerateMarkdown(result *domain.AnalysisResult) string {
	var b strings.Builder

	gateStatus := "✅ Passed"
	if result.Status == domain.GateFailed {
		gateStatus = "❌ Failed"
	}

	b.WriteString(fmt.Sprintf("## 🔍 Quality Gate: %s\n\n", gateStatus))

	// Summary table
	b.WriteString("| Check | Status | Details | Time |\n")
	b.WriteString("|-------|--------|---------|------|\n")

	for _, check := range result.Checks {
		icon := statusIcons[check.Status]
		dur := formatDuration(check.Duration)
		b.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n", check.Name, icon, check.Summary, dur))
	}
	b.WriteString("\n")

	// Failed/warning details
	for _, check := range result.Checks {
		if check.Status != domain.StatusPassed && check.Status != domain.StatusSkipped && len(check.Details) > 0 {
			icon := statusIcons[check.Status]
			b.WriteString("<details>\n")
			b.WriteString(fmt.Sprintf("<summary>%s %s — %s</summary>\n\n", icon, check.Name, check.Summary))
			b.WriteString("```\n")
			limit := min(len(check.Details), 30)
			for _, d := range check.Details[:limit] {
				b.WriteString(d + "\n")
			}
			if len(check.Details) > 30 {
				b.WriteString(fmt.Sprintf("... and %d more\n", len(check.Details)-30))
			}
			b.WriteString("```\n")
			b.WriteString("</details>\n\n")
		}
	}

	// Coverage breakdown
	for _, check := range result.Checks {
		if check.ID == "coverage" && check.Metrics != nil {
			b.WriteString("<details>\n")
			b.WriteString("<summary>📊 Coverage Breakdown</summary>\n\n")
			b.WriteString("| Metric | Value |\n")
			b.WriteString("|--------|-------|\n")
			b.WriteString(fmt.Sprintf("| Lines | %.1f%% |\n", check.Metrics["lines"]))
			b.WriteString(fmt.Sprintf("| Branches | %.1f%% |\n", check.Metrics["branches"]))
			b.WriteString(fmt.Sprintf("| Functions | %.1f%% |\n", check.Metrics["functions"]))
			b.WriteString(fmt.Sprintf("| Statements | %.1f%% |\n", check.Metrics["statements"]))
			b.WriteString("</details>\n\n")
		}
	}

	// Ratings
	if len(result.Ratings) > 0 {
		b.WriteString("### Ratings\n\n")
		for metric, rating := range result.Ratings {
			b.WriteString(fmt.Sprintf("- **%s**: %s\n", metric, string(rating)))
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n")
	b.WriteString(fmt.Sprintf("*Total time: %s · Generated by [quality-gate](https://github.com/guilherme11gr/crivo)*\n", formatDuration(result.TotalDuration)))

	return b.String()
}
