#!/usr/bin/env bash
# qg-pr-comment.sh — Post quality gate results as a PR comment
# Works with GitHub CLI (gh), GitLab API, or outputs for other platforms.
#
# Usage: ./qg-pr-comment.sh [report.md]
#
# Environment variables:
#   QG_REPORT_PATH  - Path to markdown report (default: qg-reports/report.md)
#   QG_JSON_PATH    - Path to JSON output (default: qg-reports/output.json)
#   QG_CI_PLATFORM  - "github", "gitlab", or "stdout" (default: auto-detect)
#   QG_PR_NUMBER    - PR number (default: auto-detect)
#   QG_COMMENT_TAG  - Unique tag for sticky comments (default: "quality-gate")
set -euo pipefail

REPORT="${1:-${QG_REPORT_PATH:-qg-reports/report.md}}"
JSON="${QG_JSON_PATH:-qg-reports/output.json}"
PLATFORM="${QG_CI_PLATFORM:-}"
PR_NUMBER="${QG_PR_NUMBER:-}"
TAG="${QG_COMMENT_TAG:-quality-gate}"

# ---------------------------------------------------------------------------
# Auto-detect platform
# ---------------------------------------------------------------------------
if [ -z "$PLATFORM" ]; then
  if [ -n "${GITHUB_TOKEN:-}" ] || [ -n "${GH_TOKEN:-}" ]; then
    PLATFORM="github"
  elif [ -n "${CI_MERGE_REQUEST_IID:-}" ]; then
    PLATFORM="gitlab"
  else
    PLATFORM="stdout"
  fi
fi

# ---------------------------------------------------------------------------
# Build comment body
# ---------------------------------------------------------------------------
if [ ! -f "$REPORT" ]; then
  echo "Error: report not found at $REPORT"
  echo "Run 'qg run --md $REPORT' first."
  exit 1
fi

# Add metadata footer
BODY=$(cat "$REPORT")
BODY="$BODY

---
<!-- quality-gate-comment-tag: $TAG -->
*Generated by [quality-gate](https://github.com/anthropics/quality-gate) on $(date -u +%Y-%m-%dT%H:%M:%SZ)*"

# ---------------------------------------------------------------------------
# Post comment
# ---------------------------------------------------------------------------
case "$PLATFORM" in
  github)
    # Auto-detect PR number from GitHub Actions
    if [ -z "$PR_NUMBER" ]; then
      if [ -n "${GITHUB_EVENT_NAME:-}" ] && [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
        PR_NUMBER=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH" 2>/dev/null || echo "")
      fi
    fi

    if [ -z "$PR_NUMBER" ]; then
      echo "Warning: could not detect PR number. Outputting to stdout."
      echo "$BODY"
      exit 0
    fi

    # Check for existing comment to update (sticky)
    REPO="${GITHUB_REPOSITORY:-$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || echo '')}"
    if [ -z "$REPO" ]; then
      echo "Error: could not detect repository"
      exit 1
    fi

    EXISTING_ID=$(gh api "repos/$REPO/issues/$PR_NUMBER/comments" \
      --jq ".[] | select(.body | contains(\"quality-gate-comment-tag: $TAG\")) | .id" \
      2>/dev/null | head -1 || echo "")

    if [ -n "$EXISTING_ID" ]; then
      # Update existing comment
      gh api "repos/$REPO/issues/comments/$EXISTING_ID" \
        --method PATCH \
        --field body="$BODY" > /dev/null
      echo "Updated existing PR comment (id: $EXISTING_ID)"
    else
      # Create new comment
      gh api "repos/$REPO/issues/$PR_NUMBER/comments" \
        --method POST \
        --field body="$BODY" > /dev/null
      echo "Created new PR comment"
    fi
    ;;

  gitlab)
    MR_IID="${CI_MERGE_REQUEST_IID:-$PR_NUMBER}"
    PROJECT_ID="${CI_PROJECT_ID:-}"

    if [ -z "$MR_IID" ] || [ -z "$PROJECT_ID" ]; then
      echo "Warning: GitLab MR context not available. Outputting to stdout."
      echo "$BODY"
      exit 0
    fi

    # Post comment via GitLab API
    curl -fsSL --request POST \
      --header "PRIVATE-TOKEN: ${GITLAB_TOKEN:-$CI_JOB_TOKEN}" \
      --header "Content-Type: application/json" \
      --data "$(jq -n --arg body "$BODY" '{body: $body}')" \
      "${CI_API_V4_URL:-https://gitlab.com/api/v4}/projects/$PROJECT_ID/merge_requests/$MR_IID/notes" \
      > /dev/null

    echo "Posted comment to MR !$MR_IID"
    ;;

  stdout|*)
    echo "$BODY"
    ;;
esac
